name: update json data
on:
  # push:
  #  paths:
  #    - '.github/workflows/update-data.yml'
  # pull_request:
  #   paths:
  #     - '.github/workflows/update_data.yml'
  repository_dispatch:
    types: [update_data]
  schedule:
    - cron:  '15 2,13 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout covid19
      uses: actions/checkout@v2
      with:
        ref: 'development'

    - name: Checkout covid19-scraping
      uses: actions/checkout@v2
      with:
        repository: stop-covid19-kyoto/scraping-system
        ref: 'gh-pages'
        path: 'scraping-system'

    - name: copy files
      run: |
        cp -p scraping-system/*.json data 2>/dev/null
        rm -rf scraping-system

    - run: git diff

    - name: Commit files
      continue-on-error: true
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data
        git commit -m "update json data `date '+%Y-%m-%dT%H:%M:%SZ'`"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        labels: auto_merge, deploy-ready
        token: ${{ secrets.GITHUB_TOKEN }}
        title: ${{ format('Update json data {0}', github.event.head_commit.timestamp) }}
        branch-suffix: 'short-commit-hash'
        branch: update-data
